### ISSUE TITLE
在 WSL 下运行，没有报错，但没有结果保存下来。

### ISSUE THREAD

**Issue by IceCodeNew** [BlindingDark/rime_easy_eng_dict#1]
![圖片](https://user-images.githubusercontent.com/32576256/79456784-ad6b7c00-8021-11ea-823d-b5cfb241f6a1.png)

**Comment by BlindingDark** [comment]
https://github.com/BlindingDark/rime_easy_eng_dict/blob/master/lib/mix/tasks/conver.ex#L17

把这行改成

```elixir
out = Path.expand(@out) |> IO.inspect
```

这样会打印出输出的路径，看看有没有错误

**Comment by IceCodeNew** [comment]
```mix conver ./ecdict.csv
Compiling 1 file (.ex)
"/github/rime_easy_eng_dict/out/easy_en.dict.yaml"
 converting | ZZZ       Zzz     959312USER@HOST```

**Comment by IceCodeNew** [comment]
我先把out这个目录创建出来再运行一次试试

**Comment by IceCodeNew** [comment]
自己手动创建 out 目录以后可以看到生成的文件了，我觉得代码上有值得优化的地方。
可惜我完全没接触过 erlang（（

**Comment by IceCodeNew** [comment]
感谢作者抽空回复。

**Comment by BlindingDark** [comment]
@IceCodeNew 感谢指出问题，已修复这个 bug

**Comment by IceCodeNew** [comment]
其实我自己跑一遍代码主要是想看看到底没有精简过的 `easy_en.dict.yaml` 文件有多大，然后跑下 diff 和原版的 easy_en.dict 比较有哪些地方有区别。
结果跑完发现只有 4M 大小才明白原来我用的 repo 的代码就是会精简码表的代码……

**Comment by BlindingDark** [comment]
> 其实我自己跑一遍代码主要是想看看到底没有精简过的 `easy_en.dict.yaml` 文件有多大，然后跑下 diff 和原版的 easy_en.dict 比较有哪些地方有区别。
> 结果跑完发现只有 4M 大小才明白原来我用的 repo 的代码就是会精简码表的代码……

https://github.com/BlindingDark/rime_easy_eng_dict/blob/master/lib/rime_dict.ex#L33

这里已经做了过滤了，我待会加个不过滤的版本。警告，输出的文件会非常大。。。大到卡死 rime。

**Comment by IceCodeNew** [comment]
> 警告，输出的文件会非常大。。。大到卡死 rime。

哈哈，因爲原版也有 10M，但我居然還能在手機上跑起來，所以就想看看是不是能再大一點（當然這次只會在電腦上套大詞典了
（手機 trime 用了一年多了，今天第一次注意到 easy_en.dict 的大小問題）

> 我待会加个不过滤的版本

感謝，我很期待~

**Comment by BlindingDark** [comment]
@IceCodeNew 

真的会很卡哦

```shell
ONLY_HIGH_FREQUENCY=false mix conver ./ecdict.csv
```

> 因爲原版也有 10M

原版的词汇有些重复，中间也少了一部分词。整体其实还不如小体积 4M 的词库。

**Comment by IceCodeNew** [comment]
~~我跑了一个小时了，还没有跑完，ssfd（跑完了再来更新评论 XD~~

生成了大小 40M 的码表，试着用 PC 带了下，果然带不动 XDD
